// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repository

import (
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

type DailyPrice struct {
	ID     int64
	Symbol string
	Date   time.Time
	Open   pgtype.Float8
	High   pgtype.Float8
	Low    pgtype.Float8
	Close  pgtype.Float8
	Volume pgtype.Int8
}

type Stock struct {
	Symbol    string
	Name      string
	Market    string
	CreatedAt time.Time
}

type SyncLog struct {
	ID         int64
	Triggered  string
	Status     string
	Message    string
	StartedAt  time.Time
	FinishedAt pgtype.Timestamptz
}
