// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: prices.sql

package repository

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const getDailyPricesBySymbol = `-- name: GetDailyPricesBySymbol :many
SELECT symbol, date, open, high, low, close, volume
FROM daily_prices
WHERE symbol = $1
ORDER BY date ASC
`

type GetDailyPricesBySymbolRow struct {
	Symbol string
	Date   time.Time
	Open   pgtype.Float8
	High   pgtype.Float8
	Low    pgtype.Float8
	Close  pgtype.Float8
	Volume pgtype.Int8
}

func (q *Queries) GetDailyPricesBySymbol(ctx context.Context, symbol string) ([]GetDailyPricesBySymbolRow, error) {
	rows, err := q.db.Query(ctx, getDailyPricesBySymbol, symbol)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetDailyPricesBySymbolRow
	for rows.Next() {
		var i GetDailyPricesBySymbolRow
		if err := rows.Scan(
			&i.Symbol,
			&i.Date,
			&i.Open,
			&i.High,
			&i.Low,
			&i.Close,
			&i.Volume,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDailyPricesBySymbolAndDateRange = `-- name: GetDailyPricesBySymbolAndDateRange :many
SELECT symbol, date, open, high, low, close, volume
FROM daily_prices
WHERE symbol = $1
  AND date >= $2
  AND date <= $3
ORDER BY date ASC
`

type GetDailyPricesBySymbolAndDateRangeParams struct {
	Symbol string
	Date   time.Time
	Date_2 time.Time
}

type GetDailyPricesBySymbolAndDateRangeRow struct {
	Symbol string
	Date   time.Time
	Open   pgtype.Float8
	High   pgtype.Float8
	Low    pgtype.Float8
	Close  pgtype.Float8
	Volume pgtype.Int8
}

func (q *Queries) GetDailyPricesBySymbolAndDateRange(ctx context.Context, arg GetDailyPricesBySymbolAndDateRangeParams) ([]GetDailyPricesBySymbolAndDateRangeRow, error) {
	rows, err := q.db.Query(ctx, getDailyPricesBySymbolAndDateRange, arg.Symbol, arg.Date, arg.Date_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetDailyPricesBySymbolAndDateRangeRow
	for rows.Next() {
		var i GetDailyPricesBySymbolAndDateRangeRow
		if err := rows.Scan(
			&i.Symbol,
			&i.Date,
			&i.Open,
			&i.High,
			&i.Low,
			&i.Close,
			&i.Volume,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertDailyPrice = `-- name: UpsertDailyPrice :exec
INSERT INTO daily_prices (symbol, date, open, high, low, close, volume)
VALUES ($1, $2, $3, $4, $5, $6, $7)
ON CONFLICT (symbol, date) DO UPDATE
    SET open   = EXCLUDED.open,
        high   = EXCLUDED.high,
        low    = EXCLUDED.low,
        close  = EXCLUDED.close,
        volume = EXCLUDED.volume
`

type UpsertDailyPriceParams struct {
	Symbol string
	Date   time.Time
	Open   pgtype.Float8
	High   pgtype.Float8
	Low    pgtype.Float8
	Close  pgtype.Float8
	Volume pgtype.Int8
}

func (q *Queries) UpsertDailyPrice(ctx context.Context, arg UpsertDailyPriceParams) error {
	_, err := q.db.Exec(ctx, upsertDailyPrice,
		arg.Symbol,
		arg.Date,
		arg.Open,
		arg.High,
		arg.Low,
		arg.Close,
		arg.Volume,
	)
	return err
}
