// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repository

import (
	"context"
)

type Querier interface {
	CreateSyncLog(ctx context.Context, arg CreateSyncLogParams) (SyncLog, error)
	GetDailyPricesBySymbol(ctx context.Context, symbol string) ([]GetDailyPricesBySymbolRow, error)
	GetDailyPricesBySymbolAndDateRange(ctx context.Context, arg GetDailyPricesBySymbolAndDateRangeParams) ([]GetDailyPricesBySymbolAndDateRangeRow, error)
	GetLastSyncLog(ctx context.Context) (SyncLog, error)
	GetStock(ctx context.Context, symbol string) (Stock, error)
	ListStocks(ctx context.Context) ([]Stock, error)
	UpdateSyncLog(ctx context.Context, arg UpdateSyncLogParams) error
	UpsertDailyPrice(ctx context.Context, arg UpsertDailyPriceParams) error
	UpsertStock(ctx context.Context, arg UpsertStockParams) error
}

var _ Querier = (*Queries)(nil)
