// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: stocks.sql

package repository

import (
	"context"
)

const getStock = `-- name: GetStock :one
SELECT symbol, name, market, created_at
FROM stocks
WHERE symbol = $1
`

func (q *Queries) GetStock(ctx context.Context, symbol string) (Stock, error) {
	row := q.db.QueryRow(ctx, getStock, symbol)
	var i Stock
	err := row.Scan(
		&i.Symbol,
		&i.Name,
		&i.Market,
		&i.CreatedAt,
	)
	return i, err
}

const listStocks = `-- name: ListStocks :many
SELECT symbol, name, market, created_at
FROM stocks
ORDER BY symbol
`

func (q *Queries) ListStocks(ctx context.Context) ([]Stock, error) {
	rows, err := q.db.Query(ctx, listStocks)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Stock
	for rows.Next() {
		var i Stock
		if err := rows.Scan(
			&i.Symbol,
			&i.Name,
			&i.Market,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertStock = `-- name: UpsertStock :exec
INSERT INTO stocks (symbol, name, market)
VALUES ($1, $2, $3)
ON CONFLICT (symbol) DO UPDATE
    SET name   = EXCLUDED.name,
        market = EXCLUDED.market
`

type UpsertStockParams struct {
	Symbol string
	Name   string
	Market string
}

func (q *Queries) UpsertStock(ctx context.Context, arg UpsertStockParams) error {
	_, err := q.db.Exec(ctx, upsertStock, arg.Symbol, arg.Name, arg.Market)
	return err
}
