// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: sync_logs.sql

package repository

import (
	"context"
)

const createSyncLog = `-- name: CreateSyncLog :one
INSERT INTO sync_logs (triggered, status)
VALUES ($1, $2)
RETURNING id, triggered, status, message, started_at, finished_at
`

type CreateSyncLogParams struct {
	Triggered string
	Status    string
}

func (q *Queries) CreateSyncLog(ctx context.Context, arg CreateSyncLogParams) (SyncLog, error) {
	row := q.db.QueryRow(ctx, createSyncLog, arg.Triggered, arg.Status)
	var i SyncLog
	err := row.Scan(
		&i.ID,
		&i.Triggered,
		&i.Status,
		&i.Message,
		&i.StartedAt,
		&i.FinishedAt,
	)
	return i, err
}

const getLastSyncLog = `-- name: GetLastSyncLog :one
SELECT id, triggered, status, message, started_at, finished_at
FROM sync_logs
ORDER BY started_at DESC
LIMIT 1
`

func (q *Queries) GetLastSyncLog(ctx context.Context) (SyncLog, error) {
	row := q.db.QueryRow(ctx, getLastSyncLog)
	var i SyncLog
	err := row.Scan(
		&i.ID,
		&i.Triggered,
		&i.Status,
		&i.Message,
		&i.StartedAt,
		&i.FinishedAt,
	)
	return i, err
}

const updateSyncLog = `-- name: UpdateSyncLog :exec
UPDATE sync_logs
SET status      = $2,
    message     = $3,
    finished_at = NOW()
WHERE id = $1
`

type UpdateSyncLogParams struct {
	ID      int64
	Status  string
	Message string
}

func (q *Queries) UpdateSyncLog(ctx context.Context, arg UpdateSyncLogParams) error {
	_, err := q.db.Exec(ctx, updateSyncLog, arg.ID, arg.Status, arg.Message)
	return err
}
